FEAT Add '-g *' argument
roeniss/dhlottery-api pull request #18
Opened 2023-04-19 10:12 UTC by Mikeds36

Get information on arrGameChoiceNum's trailed number #17 
In Login function, check user logged in 
Fix some information strings
Html5lib required to develop
Fix exception not to print stack trace #10 

고칠 내용이 있으시다면 댓글 남겨주세요!

2023-04-19 16:27 UTC, roeniss requested changes
우선, 기여 감사드립니다!

아래 코멘트와 더불어 Lotto645BuyRequest class 의 dostring 에도 관련하여 한 줄만 내용을 추가해주시면 감사하겠습니다.

2023-04-19 16:27 UTC, roeniss commented on docs/CONTRIBUTING.md
> +            "A|nn|nn|nn|nn|nn|nn3",  # Manual : 1, Combine : 2, Automatic : 3
와우, 감사합니다!

2023-04-19 16:27 UTC, roeniss commented on requirements.txt
> +html5lib~=1.1
"BeautifulSoup" 라이브러리 안에 "html5lib" 가 포함되어있어서 필요없다고 판단했는데, 넣어야 하는걸까요? (제가 잘 모릅니다)

2023-04-19 16:27 UTC, roeniss commented on docs/CONTRIBUTING.md
> +            "A|nn|nn|nn|nn|nn|nn3",  # Manual : 1, Combine : 2, Automatic : 3
추후 더 잘 보여줄 필요는 있겠네요

2023-04-19 16:27 UTC, roeniss commented on src/dhapi/domain_object/lotto645_buy_request.py
> +                and all(map(lambda x: x == "*" or 1 <= x <= 45, game))
이 부분은 revert 부탁드립니다. 

루트 디렉토리에서 `make lintfmt` 명령어를 이용해서 포맷을 맞출 수 있는데 가이드에 설명이 부족했네요. (black, pylint 라이브러리가 잠시 필요하실 겁니다)

2023-04-19 16:27 UTC, roeniss commented on src/dhapi/domain_object/lotto645_buy_request.py
> +            and (self._get_auto_count_in_game(game) != 1)
이 부분도 `make lintfmt` 안해서 생긴 변화이므로 revert 부탁드립니다

2023-04-19 16:27 UTC, roeniss commented on src/dhapi/client/lottery_client.py
> +            raise ValueError("로그인에 실패했습니다. \n아이디 또는 비밀번호를 확인해주세요.\n아이디는 대소문자를 구분합니다.")
와 한번에 되는군요! 정말 감사합니다.

한가지만 수정 부탁드립니다: `make lintfmt`가 안되어서 생긴 이슈같은데요, single quote (`'`)를 double quote(`"`) 로 모두 교체해주시면 감사하겠습니다.

2023-04-19 16:27 UTC, roeniss commented on src/dhapi/purchase/lotto645_controller.py
> +위와 같이 구매하시겠습니까? [[Y]/n] """,
good

2023-04-19 16:27 UTC, roeniss commented on requirements.txt
> +html5lib~=1.1
아니네요 이거 없으면 에러나네요. 기존에 사용했던 부분에선 class 를 읽진 않아서 괜찮았던 건가... 아무튼 챙겨주셔서 감사합니다.

2023-04-19 16:27 UTC, roeniss commented on src/dhapi/purchase/lotto645_controller.py
> +    # ID가 다른 경우 loginYn이 N으로 나옴
위에서 로그인 실패 상황을 걸러내주셨기 때문에 여기선 주석(L36)과 아래 코드 블럭을 제거해도 괜찮을 것 같은데 어떻게 생각하시나요? (L38-L40)

```python3
        if body.get("loginYn") != "Y":
            print("Fail to purchase (reason: not logged in)")
            return
```

2023-04-19 16:27 UTC, roeniss commented on src/dhapi/router/router.py
> +    sys.tracebacklimit = 0
이런게 있군요. 감사합니다!

2023-04-19 16:27 UTC, roeniss commented on src/dhapi/router/arg_parser.py
> +dhapi buy_lotto645 -u $USER_ID -p $USER_PW -g *  # 자동으로 1장 구매
L30과 L31 이 바뀌어야 할 것 같습니다 (`"(위 명령어의 축약형)"` 이라는 부연설명이 필요해 보여요)

2023-04-19 23:32 UTC, Mikeds36 commented on requirements.txt
> +html5lib~=1.1
여기에 추가로 make lintfmt 명령어를 실행할 때, black과 pylint 패키지가 필요합니다.
추후 requirements.txt 파일에 추가하도록 하겠습니다.

2023-04-20 00:49 UTC, roeniss commented on requirements.txt
> +html5lib~=1.1
말씀하신 두 라이브러리는 개발 단계에서만 필요한 거라서, requirements.txt 가 development / production 구분이 불가능하다면 안넣는게 좋을것 같습니다.

2023-04-20 03:10 UTC, Mikeds36 commented on src/dhapi/purchase/lotto645_controller.py
> +    # ID가 다른 경우 loginYn이 N으로 나옴
L38-L40은 혹시나 모를 문제가 발생할 가능성이 있을 것 같아 남겨두었습니다.
(ex, site layout 변경 등으로 인한 로그인 불가 현상)

2023-04-20 09:53 UTC, roeniss commented on src/dhapi/purchase/lotto645_controller.py
> +    # ID가 다른 경우 loginYn이 N으로 나옴
이 경우는 깨지도록 놔두는 것이 나을 것 같습니다. 이 에러는 사용자가 인지하고 버그로 제보해야 될 내용이라고 생각합니다. 그래야 앞부분 로그인 체크 함수를 고칠 수가 있습니다.

이 문제를 여기서 막으면 site layout 에 대한 대응을 제때 못한다고 생각합니다.

2023-04-20 09:53 UTC, roeniss commented
쓰잘데기 없는 파일이 많네요.. 반성합니다 :bow:

2023-04-20 10:01 UTC, Mikeds36 commented on src/dhapi/purchase/lotto645_controller.py
> +    # ID가 다른 경우 loginYn이 N으로 나옴
일리가 있네요.
말씀주신대로 코드블럭 제거해두겠습니다.

2023-04-20 17:33 UTC, roeniss commented on src/dhapi/purchase/lotto645_controller.py
> +    # ID가 다른 경우 loginYn이 N으로 나옴
감사합니다!

2023-04-21 00:51 UTC, roeniss commented on src/dhapi/purchase/lotto645_controller.py
> +    # ID가 다른 경우 loginYn이 N으로 나옴
요건 완료되시면 멘션 한번만 부탁드립니다 :bow: @Mikeds36

2023-04-21 03:06 UTC, Mikeds36 commented on src/dhapi/purchase/lotto645_controller.py
> +    # ID가 다른 경우 loginYn이 N으로 나옴
@roeniss 코드블럭 제거하고 리뷰 요청드렸습니다!

2023-04-21 16:09 UTC, roeniss approved these changes
멋지고 장대한 기여 감사합니다. 그리고 수고하셨습니다!

2023-04-21 16:11 UTC, merged

2023-04-24 16:49 UTC, roeniss commented
@Mikeds36 말씀드리는 것을 깜빡했는데, v1.3.1 을 사용해주시면 됩니다!

```
pip install --upgrade dhapi
```