Implement semi-auto and manual modes
roeniss/dhlottery-api pull request #31
Opened 2023-05-07 09:09 UTC by dhoon-dev

* Rename 'half-auto' keyword to 'semi-auto'.
* Semi-auto and manual modes work fine.
* Change -g,--game value format:
  - manual mode: -g 1,2,3,4,5,6
  - semi-auto mode (two automatic numbers): -g 1,2,3,4
  - auto mode: -g auto

2023-05-07 09:28 UTC, dhoon-dev commented
<img width="1062" alt="dhlottery_api_test_result" src="https://user-images.githubusercontent.com/6831401/236669310-83c765a7-5338-48aa-b127-f6dcf18c8b5f.png">

2023-05-07 15:44 UTC, roeniss commented
우선 기여해주셔서 너무 감사드립니다! 설마 두 번째 기여자가 나타나실 거라곤 생각하지 못했습니다...

1. PR 최상단에 `- resolves #32` 을 추가해주세요. 이 PR 이 머지되었을 때 해당 이슈가 자동으로 클로즈 될 것입니다.
2. -g 의 인자를 "부분적"으로 넣는 것은 매우 좋은 것 같습니다. 그러면 나아가, **아예 인자를 주지 않는 경우에 auto 인 것으로 간주하면 어떨까요?** `-g 1,2,3,4,5,6` >> `-g 1,2,3` >> `-g` 순서로 모드가 바뀌는 것이 직관적일 것 같아요.
3. lotter_client.py 쪽에 `HALF_AUTO` 가 남아있는데 `SEMI_AUTO` 로 바꾸는 것이 좋을 것 같습니다. 나머진 다 고쳐주신 것 같네요..
4. `[Lottery645 Buy Request]` 부분에서, 구매하지 않는 경우와 자동모드로 구매하는 경우를 구분하는 것이 좋을 것 같습니다. 

    ```
    // dhapi buy_lotto645 -g -g 1,2,3 -g 1,2,3,4,5,6
    [Lottery645 Buy Request]
    Game 
    Game 
    Game 
    ```

2023-05-07 15:54 UTC, roeniss commented
@dhoon-dev 추가로, 코드 부분은 아직 보지 못했는데요, 제가 그 사이 PR 머지 시킨게 많아서 rebase 한번만 해주시면 감사하겠습니다.

2023-05-08 09:01 UTC, dhoon-dev commented
> 우선 기여해주셔서 너무 감사드립니다! 설마 두 번째 기여자가 나타나실 거라곤 생각하지 못했습니다...
> 
> 1. PR 최상단에 `- resolves #32` 을 추가해주세요. 이 PR 이 머지되었을 때 해당 이슈가 자동으로 클로즈 될 것입니다.
> 2. -g 의 인자를 "부분적"으로 넣는 것은 매우 좋은 것 같습니다. 그러면 나아가, **아예 인자를 주지 않는 경우에 auto 인 것으로 간주하면 어떨까요?** `-g 1,2,3,4,5,6` >> `-g 1,2,3` >> `-g` 순서로 모드가 바뀌는 것이 직관적일 것 같아요.
> 3. lotter_client.py 쪽에 `HALF_AUTO` 가 남아있는데 `SEMI_AUTO` 로 바꾸는 것이 좋을 것 같습니다. 나머진 다 고쳐주신 것 같네요..
> 4. `[Lottery645 Buy Request]` 부분에서, 구매하지 않는 경우와 자동모드로 구매하는 경우를 구분하는 것이 좋을 것 같습니다.
>    ```
>    // dhapi buy_lotto645 -g -g 1,2,3 -g 1,2,3,4,5,6
>    [Lottery645 Buy Request]
>    Game A: []
>    Game B: [1,2,3]
>    Game C: [1,2,3,4,5,6]
>    Game D: None
>    Game E: None
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    이렇게 보일 것 같아서, A와 D/E 를 구분할 수 있으면 좋을 것 같은데 어떻게 생각하시나요?

1~3번은 모두 수정했고,
4번은 요청이 들어온 만큼만 출력하도록 되어 있습니다.
```
// dhapi buy_lotto645 -g -g 1,2,3 -g 1,2,3,4,5,6
[Lottery645 Buy Request]
Game A: []
Game B: [1,2,3]
Game C: [1,2,3,4,5,6]
```

2023-05-14 08:53 UTC, roeniss requested changes
코드 코멘트 쪽에도 적어두었지만, 추가로 리뷰한 부분들은 의무가 아닙니다 (제가 추가로 커버할 수 있을 것 같습니다). request changes 눌러둘테니, 다시 저에게 리뷰 요청 주시길 부탁드립니다. 요청 주셨을 때 추가로 커밋 올라온 게 없다면 뒷작업은 저한테 맡기신 거라고 이해하겠습니다~!

2023-05-14 08:53 UTC, roeniss commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        - This example shows three auto games, a semi-auto game and a manual game.
nit: 'a' -> 'one'

2023-05-14 08:53 UTC, roeniss commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        # fmt: off
수동으로 fmt 를 끄고 키는 것은 좋지 않은 패턴이라고 생각합니다. 만약 그런게 필요하다면 아예 .pylintrc 쪽에서 disable 시키는게 낫지 않을까 싶은데요, 여러줄로 이루어진 return 값을 사용하면서 fmt 코멘트를 넣지 않는 방법은 없을까요?

2023-05-14 08:53 UTC, roeniss commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        - This example shows three auto games, a semi-auto game and a manual game.
nit: 'a' -> 'one'

2023-05-14 08:53 UTC, roeniss commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        # fmt: off
임의로, 부분적으로 린트를 껐다 키는 것은 좋지 않은 패턴으로 보입니다. 기본적으로 pylint 의 포맷팅 방식에 크게 불만이 없지만, 만약 바꾸고 싶으시면 `./.pylintrc` 파일을 수정해주시길 부탁드립니다.

2023-05-14 08:53 UTC, roeniss commented on src/dhapi/domain_object/lotto645_buy_request.py
> +
RuntimeError 와 한글 메시지로 통일하려고 노력하는 중입니다. [이 부분](https://github.com/roeniss/dhlottery-api/blob/dd0137c2c1f965495008ef4aee818f14251ab4b0/src/dhapi/client/lottery_client.py#L47-L55) 을 참고해서 고쳐주실 수 있으실까요? (애매하면 머지 후 제가 손대겠습니다)

2023-05-14 08:53 UTC, roeniss commented on src/dhapi/purchase/lotto645_controller.py
> -            raise NotImplementedError("반자동 입력은 아직 구현되지 않았습니다. 필요하시면 이슈를 남겨주세요.")
여기도 RunetimeError 로 변경해주시면 감사하겠습니다

2023-05-14 08:54 UTC, roeniss commented
![Screenshot 2023-05-14 at 17 53 28 by seonghyeok](https://github.com/roeniss/dhlottery-api/assets/26613280/ec93cce9-7a31-4db3-91d1-8ced98becd85) 제가 표현을 이상하게 했을까봐 이미지도 남깁니다! @dhoon-dev

2023-05-14 11:11 UTC, dhoon-dev commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        - This example shows three auto games, a semi-auto game and a manual game.
one으로 수정했습니다.

2023-05-14 11:16 UTC, dhoon-dev commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        # fmt: off
pylint 문제는 아니고, black의 reformat 문제입니다.
(black 없이 pylint만 돌리면, 100% 만족합니다.)

black에서 multiple line을 single line으로 wrap하는데, 이걸 방지하는 방법은 fmt 코멘트로 reformat을 방지하는 방법 밖에 없는 것으로 압니다.
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html


single line 으로 변경된 걸 보시면 아시겠지만... 가독성이 상당히 안좋아집니다.

이 부분은 나중에 해결 방법이 생기면, 수정하시는게 나을 듯 합니다.

2023-05-14 11:18 UTC, dhoon-dev commented on src/dhapi/purchase/lotto645_controller.py
> -            raise NotImplementedError("반자동 입력은 아직 구현되지 않았습니다. 필요하시면 이슈를 남겨주세요.")
자동/반자동 모두 구현이되어 해당 라인은 이미 삭제되었습니다.

2023-05-14 11:20 UTC, dhoon-dev commented on src/dhapi/domain_object/lotto645_buy_request.py
> +
한글 메세지로 변경하고, RuntimeError로 변경하였습니다.

해당 에러들은 사용자가 볼일은 없고, API개발시에나 확인할 수 있는 에러입니다. 전 정확한 에러 타입을 설정하는 것을 선호하지만 프로젝트 정책에 따라 변경합니다.

2023-05-14 11:21 UTC, dhoon-dev commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        # fmt: off
pylint 문제는 아니고, black의 reformat 문제입니다.
(black 없이 pylint만 돌리면, 100% 만족합니다.)

black에서 multiple line을 single line으로 wrap하는데, 이걸 방지하는 방법은 fmt 코멘트로 reformat을 방지하는 방법 밖에 없는 것으로 압니다.
https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html

single line 으로 변경된 걸 보시면 아시겠지만... 가독성이 상당히 안좋아집니다.

이 부분은 나중에 해결 방법이 생기면, 수정하시는게 나을 듯 합니다.

2023-05-14 11:39 UTC, dhoon-dev commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        - This example shows three auto games, a semi-auto game and a manual game.
one으로 수정했습니다.

2023-05-14 11:49 UTC, dhoon-dev commented
@roeniss 
수정할건 수정해서 올렸고, 리뷰에 모두 코멘트 달아뒀습니다.

2023-05-14 22:32 UTC, roeniss commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        # fmt: off
그렇군요.. [# fmt: skip](https://stackoverflow.com/questions/58584413/black-formatter-ignore-specific-multi-line-code#comment123224606_58584557) 을 이용하면 한줄로도 될 것 같지만 별로 중요한 부분은 아닌것 같습니다. OK 입니다

2023-05-14 22:32 UTC, roeniss commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        # fmt: off
https://github.com/roeniss/dhlottery-api/pull/31#discussion_r1193219468

2023-05-14 22:36 UTC, dhoon-dev commented on src/dhapi/domain_object/lotto645_buy_request.py
> +        # fmt: off
skip 해봤는데 적용이 안되드라구요🤔

2023-05-15 00:41 UTC, roeniss commented
수고하셨습니다!

2023-05-15 00:41 UTC, roeniss approved these changes

2023-05-15 00:43 UTC, merged