GitHub Actions 방법 추가
roeniss/dhlottery-api pull request #40
Opened 2023-05-15 14:32 UTC by seongilp

github 액션 방법 추가

2023-05-16 15:16 UTC, seonghyeok-moon requested changes
우선 기여해주셔서 감사합니다! 리뷰 남겼습니다 🙇

2023-05-16 15:16 UTC, seonghyeok-moon commented on .github/workflows/action.yml
> +    - cron: '55 23 * * 0' # UST 기준의 크론. UST 23:55 는 KST 08:55, 0은 Sunday
```suggestion
    - cron: '55 23 * * 0' # 한국시간 기준 매주 일요일 오전 8시 55분
```

2023-05-16 15:16 UTC, seonghyeok-moon commented on .github/workflows/action.yml
> +
이 줄이 빈 줄이어야 하는데 `          `의 whitespace 로 채워져 있습니다. 전체적으로 format 을 한번 돌려주시면 감사하겠습니다. 

https://codebeautify.org/markdown-formatter 이런 사이트를 써보시면 될 듯 합니다.

2023-05-16 15:16 UTC, seonghyeok-moon commented on .github/workflows/action.yml
> +#on: [push]
(L5, L33)

2023-05-16 15:16 UTC, seonghyeok-moon commented on README.md
> +* https://github.com/seongilp/dhlottery-api/blob/main/.github/workflows/action.yml 수정하여 일정 조정
```suggestion
- [github action의 schedule](.github/workflows/action.yml#L5) 수정하여 일정 조정
```

2023-05-16 15:22 UTC, roeniss requested changes
우선 기여해주셔서 감사합니다! 리뷰 남겼습니다 🙇

2023-05-16 15:22 UTC, roeniss commented on .env.sample
이 파일은 필요 없어 보입니다.

2023-05-16 15:22 UTC, roeniss commented on .github/workflows/action.yml
파일 이름이 action name 과 비슷한게 좋을 듯 합니다.

2023-05-16 15:22 UTC, roeniss commented on .github/workflows/action.yml
> +name: Automatic Lotto Buy
lotto645 를 명시해주실 수 있나요? 지금은 lotto645 밖에 없어서 조금 부끄럽습니다만, 엄밀히 말하면 다른 타입의 lotto 들도 존재해서요.

그리고 Buy 가 앞에 오는게 좋지 않을까 생각해봅니다. (e.g., Buy weekly lotto645)

2023-05-16 15:22 UTC, roeniss commented on .github/workflows/action.yml
> +#on: [push]
테스트에 사용된 것으로 보이는 주석 라인이 군데군데 보입니다. 전체적으로 한 번 정리해주세요.

2023-05-16 15:22 UTC, roeniss commented on .github/workflows/action.yml
> +    - cron: '55 23 * * 0' # UST 기준의 크론. UST 23:55 는 KST 08:55, 0은 Sunday
```suggestion
    - cron: '55 23 * * 0' # 한국시간 기준 매주 일요일 오전 8시 55분
```

2023-05-16 15:22 UTC, roeniss commented on .github/workflows/action.yml
> +        description: 'Test scenario tags'
이 부분 필요할까요?

2023-05-16 15:22 UTC, roeniss commented on .github/workflows/action.yml
> +          pip install dhapi
아래 L23 에서 dhapi 에 필요한 의존성을 모두 받기 때문에 L20의 `pip install -r requirements.txt` 은 필요 없을 것 같습니다.

2023-05-16 15:22 UTC, roeniss commented on .github/workflows/action.yml
> +
이 줄이 빈 줄이어야 하는데 `          `의 whitespace 로 채워져 있습니다. 전체적으로 format 을 한번 돌려주시면 감사하겠습니다. 

https://codebeautify.org/markdown-formatter 이런 사이트를 써보시면 될 듯 합니다.

2023-05-16 15:22 UTC, roeniss commented on .github/workflows/action.yml
> +      - name: Run!
```suggestion
      - name: Buy
```

2023-05-16 15:22 UTC, roeniss commented on .github/workflows/action.yml
> +            PASSWORD: ${{ secrets.USER_PW }}
가능한지 잘 모르겠는데, env 를 설정하는 이 블록이, env 를 사용하는 블록보다 더 위에 있으면 좋겠습니다.

2023-05-16 15:22 UTC, roeniss commented on README.md
> +* 이 repo를 fork 합니다.
여기 사이에 한 칸 띄어주시면 감사하겠습니다.

2023-05-16 15:22 UTC, roeniss commented on README.md
> +  * USER_PW : 패스워드
이 문서의 상단에 `-` 하이픈을 이용한 list 마크업을 쓰는데요, 해당 부분과 동일한 포맷을 사용해주시면 감사하겠습니다.

2023-05-16 15:22 UTC, roeniss commented on README.md
> +* https://github.com/seongilp/dhlottery-api/blob/main/.github/workflows/action.yml 수정하여 일정 조정
```suggestion
- [github action의 schedule](.github/workflows/action.yml#L5) 수정하여 일정 조정
```

2023-05-17 02:23 UTC, seongilp commented
@roeniss 상세한 리뷰 감사합니다! 수정 후 다시 PR 올릴게요!

2023-05-17 02:51 UTC, seongilp commented on .github/workflows/action.yml
> +        description: 'Test scenario tags'
workflow_dispatch만 남기고 제거 하겠습니다!

2023-05-17 03:00 UTC, seongilp commented on .github/workflows/action.yml
> +            PASSWORD: ${{ secrets.USER_PW }}
이거는 안되네요 ㅜㅜ

2023-05-17 12:48 UTC, roeniss commented
@seongilp 다 되시면 멘션 한번 주세요 :)

2023-05-17 13:48 UTC, seongilp commented
@roeniss 님! 혹시 이거 제 repo에서만 수정하면 되는거죠? 그럼 따로 PR 올릴 필요 없는걸까요?

2023-05-17 13:49 UTC, roeniss commented
@seongilp 네! 위에 보이는 것처럼 이 PR 에도 계속 변경사항이 누적중입니다 ㅎㅎ

2023-05-18 02:14 UTC, seongilp commented
@roeniss 완료되었습니다!!

2023-05-21 05:58 UTC, seongilp commented
오늘 자동스케쥴로 실행되었는데 이런 에러가 나네요 ㅜ.ㅜ
2023-05-21 05:58:00 [error    ] 🚨 에러가 발생했습니다: Expecting value: line 6 column 1 (char 5)

2023-05-21 05:59 UTC, roeniss commented
@seongilp 아직 완료되지 않은 것으로 파악되어 (계속 커밋이 추가되어) 클로즈 하겠습니다. 이후 완성되면 재 PR 부탁드립니다!

아울러, 위 커밋 메시지가 부적절하게 verbose 하고, 메시지가 큰 의미가 없어 보입니다. rebase 등을 이용해 커밋을 좀 더 타이트하게 합쳐서 다시 올려주시길 권장합니다. (따로 그렇게 하지 않으셔도 squash merge 할 것이기 때문에 큰 상관은 없지만, @seongilp 님에게 좋은 연습이 될 것으로 보입니다)

2023-05-21 06:00 UTC, closed without merging

2023-05-21 06:16 UTC, roeniss commented
@seongilp 잠깐 봤는데, 제 생각엔 pip 가 최신 버전이 아니어서 dhapi 가 최신버전대신 구버전을 쓴 것 같아요.

pip 업데이트 하는 단계와, (혹시 모르니) dhapi 버전 찍어보는 단계 (`--version`)를 추가해보시지요.

2023-05-21 06:16 UTC, roeniss commented
이 코멘트에선 답변을 종료하고, 이후 질의는 https://github.com/roeniss/dhlottery-api/issues/12 이쪽에서 부탁드립니다.