Create lintfmt.yml #37
roeniss/dhlottery-api pull request #60
Opened 2024-01-02 07:54 UTC by Mikeds36

CI: 린트 돌리는 깃헙액션 추가
#37

2024-01-03 17:08 UTC, roeniss commented
주말에 확인할게요! 기여 감사합니다.

2024-01-06 03:43 UTC, roeniss approved these changes

2024-01-06 03:43 UTC, roeniss commented on .github/workflows/lintfmt.yml
> +      uses: actions/setup-python@v2
크게 문제가 없다면, checkout, setup-python 버전을 올릴 수 있을까요?

https://github.com/actions/setup-python#basic-usage

2024-01-06 03:43 UTC, roeniss commented on .github/workflows/lintfmt.yml
> +        python-version: '3.8'
3.10 이 좋겠습니다!

2024-01-06 03:44 UTC, roeniss requested changes
(실수로 Approve 눌러서, Request Changes 로 재변경)

2024-01-07 14:20 UTC, Mikeds36 commented on .github/workflows/lintfmt.yml
> +      uses: actions/setup-python@v2
각각의 버전을 올렸습니다!
checkout v3 -> v4
setup-python v2 ->  v5

2024-01-07 14:20 UTC, Mikeds36 commented on .github/workflows/lintfmt.yml
> +        python-version: '3.8'
python version도 3.10으로 수정했습니다!

2024-01-07 18:08 UTC, roeniss approved these changes
lgtm. 기여 감사드립니다!

2024-01-07 18:08 UTC, merged