계정정보 입력기능 추가
roeniss/dhlottery-api pull request #63
Opened 2024-01-17 00:44 UTC by rlatn1234

계정정보 입력기능 추가
#62

2024-01-18 00:58 UTC, roeniss commented
주말에 확인 진행하겠습니다 🙇

2024-01-21 15:17 UTC, roeniss requested changes
세 가지 요청사항이 있습니다.

1. `read_credentials_file`, `add_credentials` 두 메서드는 앞에 underscore (`_`) 를 붙여 private method 임을 가볍게 표시해주면 좋겠습니다.
2. 흐름을 명확히 하기 위해, `get_credentials` 가 맨 위 또는 맨 아래에 위치하면 좋겠습니다 (두 private method 의 사이가 아니라)
3. 현재는 파일을 overwrite 하는 것 같습니다. default 외의 profile 이 있다면 해당 내용이 날아갈 것으로 보입니다. 따라서 default profile 추가 로직을 `append` 형태로 변경할 수 있을까요?

2024-01-22 01:47 UTC, rlatn1234 commented
> 세 가지 요청사항이 있습니다.
> 
> 1. `read_credentials_file`, `add_credentials` 두 메서드는 앞에 underscore (`_`) 를 붙여 private method 임을 가볍게 표시해주면 좋겠습니다.
> 2. 흐름을 명확히 하기 위해, `get_credentials` 가 맨 위 또는 맨 아래에 위치하면 좋겠습니다 (두 private method 의 사이가 아니라)
> 3. 현재는 파일을 overwrite 하는 것 같습니다. default 외의 profile 이 있다면 해당 내용이 날아갈 것으로 보입니다. 따라서 default profile 추가 로직을 `append` 형태로 변경할 수 있을까요?

1번과 2번 내용은 수정하도록 하겠습니다

3번은 파일의 기존 내용을 읽어와서 새 데이터를 추가 한 후에 파일에 overwrite 하는 구조로 되어있으나, 수정을 원하신다면 다른방법을 찾아보겠습니다.

2024-01-22 17:32 UTC, roeniss commented
+) CI 에서 뱉는 `W0707` 에러는 무시해주세요. 따로 제가 처리하겠습니다..

2024-02-04 07:58 UTC, roeniss commented
@rlatn1234 혹시 괜찮으시면 제가 이어서 마무리해도 될가요? 사소한 변경점들이라 제가 해도 괜찮을 것 같다는 생각이 들었습니다.

2024-02-06 07:12 UTC, rlatn1234 commented
> @rlatn1234 혹시 괜찮으시면 제가 이어서 마무리해도 될가요? 사소한 변경점들이라 제가 해도 괜찮을 것 같다는 생각이 들었습니다.

네 그렇게 해주셔도 될 것 같습니다.

2024-02-09 16:34 UTC, roeniss approved these changes
수고하셨습니다. 머지할게요!

2024-02-09 16:36 UTC, merged