(#64) docs: user credential snippet 개선
roeniss/dhlottery-api pull request #65
Opened 2024-01-18 07:40 UTC by SeungHo0422

value를 저장할 시 쌍따옴표를 추가함으로써 사용자 경험을 개선하였습니다.
우선 문서작업으로만 개선한 뒤, 추후 작업을 통해 리팩토링을 통한 개선까지도 작업해보겠습니다.

2024-01-18 09:00 UTC, roeniss commented
주말에 확인하겠습니다. 감사합니다!


2024년 1월 18일 (목) 오후 4:40, Seungho Song ***@***.***>님이 작성:

> value를 저장할 시 쌍따옴표를 추가함으로써 사용자 경험을 개선하였습니다.
> 우선 문서작업으로만 개선한 뒤, 추후 작업을 통해 리팩토링을 통한 개선까지도 작업해보겠습니다.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/roeniss/dhlottery-api/pull/65
> Commit Summary
>
>    - 8425c9c
>    <https://github.com/roeniss/dhlottery-api/pull/65/commits/8425c9cbc092b0b02d079b645d25a6bb59b062f8>
>    (#64) docs: add double quote in user credential example
>
> File Changes
>
> (1 file <https://github.com/roeniss/dhlottery-api/pull/65/files>)
>
>    - *M* README.md
>    <https://github.com/roeniss/dhlottery-api/pull/65/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5>
>    (9)
>
> Patch Links:
>
>    - https://github.com/roeniss/dhlottery-api/pull/65.patch
>    - https://github.com/roeniss/dhlottery-api/pull/65.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/roeniss/dhlottery-api/pull/65>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGLBMIE2CABGQ4QPFA4NGYLYPDGYJAVCNFSM6AAAAABB7ZQBUSVHI2DSMVQWIX3LMV43ASLTON2WKOZSGA4DONRZHE3DENI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-01-21 15:02 UTC, roeniss requested changes
```
["qwer"]
username = "qwer"
password = "5678"
```

이렇게 만들어지는데, 

```
[qwer]
username = "qwer"
password = "5678"
```

이렇게 만들어져야 할 것 같습니다. 수정을 부탁드려도 될까요? 🙇

2024-01-21 18:36 UTC, SeungHo0422 commented
말씀해주신 ["qwer"]로 표시되는 현상을 개선했습니다.
: DHAPI_USERNAME의 변수 substring을 활용하여 [qwer]로 나오게끔 구현하였습니다.
추가적으로, 사용자들에게 하여금 \"{username}\"으로 작성하도록 WARNING 콜아웃을 삽입하였습니다.

2024-01-21 18:39 UTC, SeungHo0422 reviewed
말씀해주신 ["qwer"]로 표시되는 현상을 개선했습니다.
: DHAPI_USERNAME의 변수 substring을 활용하여 [qwer]로 나오게끔 구현하였습니다.
추가적으로, 사용자들에게 하여금 "{username}"으로 작성하도록 WARNING 콜아웃을 삽입하였습니다.

2024-01-22 17:31 UTC, roeniss approved these changes
감사합니다. 수고하셨습니다!

2024-01-22 17:32 UTC, merged